// Open a PR against the client's repo with generated diffs.
// Uses @octokit/rest. Falls back to rendering the diff if GITHUB_TOKEN is
// missing or auth takes more than 20 seconds per the PRD constraint.
//
// Strategy: create a new branch, commit each Action as a file, open a PR
// with a summary of all changes. If the repo is not writeable (stranger's
// repo), the PRD says to render the diff in the UI instead — we return
// diffs as fallback.

import { Octokit } from "@octokit/rest";
import type { Action } from "../contract";

const PR_TIMEOUT_MS = 20_000;

interface PushResult {
  pr_url: string | null;
  fallback: boolean;
  reason?: string;
}

function parseRepo(repo: string): { owner: string; repo: string } | null {
  const parts = repo.replace(/^https?:\/\/github\.com\//, "").replace(/\.git$/, "").split("/");
  if (parts.length >= 2) return { owner: parts[0], repo: parts[1] };
  return null;
}

function actionToFile(action: Action): { path: string; content: string } | null {
  switch (action.type) {
    case "meta":
    case "schema":
      return { path: action.file, content: action.after };
    case "robots_txt":
      return { path: action.file, content: action.after };
    case "llms_txt":
      return { path: action.file, content: action.after };
    case "new_page":
      return { path: action.file, content: action.after };
    case "backlink_call":
      return null; // no file to commit
    default:
      return null;
  }
}

function buildPrBody(actions: Action[]): string {
  const lines = ["## CITED — AI answer engine visibility fixes", ""];
  for (const a of actions) {
    lines.push(`### ${a.type}: ${actionToFile(a)?.path ?? "N/A"}`);
    if (a.type === "new_page") {
      lines.push(`Targets keyword: **${(a as any).targets_keyword ?? "?"}**`);
    }
    if ((a as any).rationale) {
      lines.push(`> ${(a as any).rationale}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

export async function openPR(
  repo: string,
  actions: Action[],
  opts?: { branch?: string; commitMsg?: string }
): Promise<PushResult> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    return { pr_url: null, fallback: true, reason: "GITHUB_TOKEN not set" };
  }

  const parsed = parseRepo(repo);
  if (!parsed) {
    return { pr_url: null, fallback: true, reason: `Invalid repo format: ${repo}` };
  }

  const files = actions.map(actionToFile).filter((f): f is { path: string; content: string } => f !== null);
  if (!files.length) {
    return { pr_url: null, fallback: true, reason: "No committable files in actions" };
  }

  const octokit = new Octokit({ auth: token, request: { timeout: PR_TIMEOUT_MS } });
  const branch = opts?.branch ?? `cited/fix-visibility-${Date.now()}`;
  const commitMsg = opts?.commitMsg ?? "fix: improve AI answer engine visibility\n\nGenerated by CITED.";

  try {
    // Get default branch ref
    const { data: repoData } = await octokit.repos.get({ owner: parsed.owner, repo: parsed.repo });
    const defaultBranch = repoData.default_branch;

    // Get the SHA of the default branch
    const { data: refData } = await octokit.git.getRef({
      owner: parsed.owner,
      repo: parsed.repo,
      ref: `heads/${defaultBranch}`,
    });
    const baseSha = refData.object.sha;

    // Create blobs for each file
    const blobs = await Promise.all(
      files.map((f) =>
        octokit.git.createBlob({
          owner: parsed.owner,
          repo: parsed.repo,
          content: Buffer.from(f.content).toString("base64"),
          encoding: "base64",
        })
      )
    );

    // Create a tree with all files
    const { data: tree } = await octokit.git.createTree({
      owner: parsed.owner,
      repo: parsed.repo,
      base_tree: baseSha,
      tree: files.map((f, i) => ({
        path: f.path,
        mode: "100644" as const,
        type: "blob" as const,
        sha: blobs[i].data.sha,
      })),
    });

    // Create a commit
    const { data: commit } = await octokit.git.createCommit({
      owner: parsed.owner,
      repo: parsed.repo,
      message: commitMsg,
      tree: tree.sha,
      parents: [baseSha],
    });

    // Create the branch
    await octokit.git.createRef({
      owner: parsed.owner,
      repo: parsed.repo,
      ref: `refs/heads/${branch}`,
      sha: commit.sha,
    });

    // Open the PR
    const { data: pr } = await octokit.pulls.create({
      owner: parsed.owner,
      repo: parsed.repo,
      title: "fix: improve AI answer engine visibility (CITED)",
      head: branch,
      base: defaultBranch,
      body: buildPrBody(actions),
    });

    return { pr_url: pr.html_url, fallback: false };
  } catch (err: any) {
    const reason = err?.status === 403 ? "403 Forbidden (no write access to repo)" : err?.message ?? String(err);
    return { pr_url: null, fallback: true, reason };
  }
}
